# Local testing only
services:
  fxserver:
    build:
      context: .
      dockerfile: dockerfile
    container_name: fxserver
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "30120:30120/tcp"
      - "30120:30120/udp"
      - "40120:40120/tcp"
    volumes:
      - server-data:/home/container
    env_file:
      - .env
    environment:
      - TERM=xterm
      # Simulates what Pterodactyl sets as the STARTUP command
      - STARTUP=$(pwd)/alpine/opt/cfx-server/ld-musl-x86_64.so.1 --library-path "$(pwd)/alpine/usr/lib/v8/:$(pwd)/alpine/lib/:$(pwd)/alpine/usr/lib/" -- $(pwd)/alpine/opt/cfx-server/FXServer +set citizen_dir $(pwd)/alpine/opt/cfx-server/citizen/

volumes:
  server-data:
    driver: local