name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'redm.json'
      - 'egg-*.json'
      - 'README.md'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variables
        id: vars
        run: |
          # Get the short commit hash
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
          
          # Docker tags must be entirely lowercase. If your GitHub username has uppercase letters, this prevents build failures.
          echo "REPO_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/${{ env.REPO_LC }}/fxserver-docker:latest
            ghcr.io/${{ env.REPO_LC }}/fxserver-docker:${{ env.COMMIT_SHORT_SHA }}